graphics: attempt to fix build error on win32
gl_api.c++(719): error C2672: 'aw::gl::get_proc': no matching overloaded function found

I suspect this error is due to __stdcall changing the pointer type. To
fix this, I changed get_proc to accept any function pointer.