io: Fix 'missing vtable' linker error
Missing '= 0' caused following errors:
../lib/libhrplatform.so: undefined reference to `typeinfo for hrengin::io::IDirectory'
../lib/libhrplatform.so: undefined reference to `vtable for hrengin::io::IDirectory'
Because implementation for a 'non-pure' virtual turned out to be missing.